spring:
   application:
      name: client-service
   cloud:
      config:
         discovery:
            enabled: true
            serviceId: config-server
eureka:
   instance:
      securePortEnabled: true
      nonSecurePortEnabled: false
      securePort: ${PORT:8091}
      statusPageUrl: https://localhost:${eureka.instance.securePort}/info
      healthCheckUrl: https://localhost:${eureka.instance.securePort}/health
      homePageUrl: https://localhost:${eureka.instance.securePort}
   client:
      securePortEnabled: true
      serviceUrl:
         defaultZone: https://user:password@localhost:8761/eureka/
security:
   require-ssl: true
server:
   port: ${PORT:8091}
   ssl:
      enabled: true
      key-store: classpath:client.jks
      key-store-password: mountasser
      key-alias: client
